version: '2'
services:
    opinions-mongodb:
        container_name: opinions-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/opinions/mongodb/:/data/db/
